name: Build and Deploy (Astro → GitHub Pages)
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Detect package manager
        id: pm
        run: |
          echo "PM=$(node -p \"require('./package.json').packageManager || ''\" || true)" >> $GITHUB_ENV
          echo "HAS_PNPM=$([ -f pnpm-lock.yaml ] && echo true || echo false)" >> $GITHUB_ENV
          echo "HAS_YARN=$([ -f yarn.lock ] && echo true || echo false)" >> $GITHUB_ENV
          echo "HAS_NPM=$([ -f package-lock.json ] && echo true || echo false)" >> $GITHUB_ENV
      - name: Install deps
        run: |
          corepack enable || true
          if [[ "$PM" == pnpm* || "$HAS_PNPM" == "true" ]]; then
            pnpm install --frozen-lockfile || pnpm install
          elif [[ "$PM" == yarn* || "$HAS_YARN" == "true" ]]; then
            yarn install --frozen-lockfile || yarn install
          else
            if [[ "$HAS_NPM" == "true" ]]; then
              npm ci
            else
              npm install
            fi
          fi
      - name: Build
        run: |
          if [[ "$PM" == pnpm* || "$HAS_PNPM" == "true" ]]; then
            pnpm run build
          elif [[ "$PM" == yarn* || "$HAS_YARN" == "true" ]]; then
            yarn build
          else
            npm run build
          fi
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
